framework:
  default_locale: ru
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - ru
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
